import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatAutocompleteModule,
  MatBadgeModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
} from '@angular/material';
import {SortByCreatedAtPipe} from '../pipes/sort-by-created-at/sort-by-created-at.pipe';
import {StatusFilterPipe} from 'app/pipes/status_filter_pipe/status-filter.pipe';
import {StatusFilterComponent} from '../page-component/status-filter/status-filter.component';
import {StatusFilterBarComponent} from '../page-component/status-filter-bar/status-filter-bar.component';
import {StatisticFilterPipe} from '../pipes/statistic-filter/statistic-filter.pipe';
import {VirtualscrollPipe} from '../pipes/virtual-scroll/virtualscroll.pipe';
import {SearchPipe} from '../pipes/search/search.pipe';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {ResultValueComponent} from 'app/page-component/result-value/result-value.component';
import {SortByUpdatedAtPipe} from '../pipes/sort-by-created-at/sort-by-updated-at.pipe';
import {SelectedElementPipe} from '../pipes/selected-element/selected-element.pipe';

@NgModule({
  declarations: [SortByUpdatedAtPipe,
    SelectedElementPipe,
    SortByCreatedAtPipe,
    StatusFilterPipe,
    StatusFilterComponent, StatusFilterBarComponent, StatisticFilterPipe, VirtualscrollPipe, SearchPipe, ResultValueComponent],
  imports: [
    CommonModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    FormsModule,
    ReactiveFormsModule
  ],
  exports: [
    StatusFilterComponent,
    StatusFilterBarComponent,
    ResultValueComponent,
    SortByCreatedAtPipe,
    StatusFilterPipe,
    StatisticFilterPipe,
    VirtualscrollPipe,
    SortByUpdatedAtPipe,
    SearchPipe,
    SelectedElementPipe,
    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    FormsModule,
    ReactiveFormsModule,
    CommonModule
  ]
})
export class AppMaterialModule { }
