name: Karma Jasmine Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  units:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t jasmine -f ./unit-test-runner/Dockerfile .

    - name: Run test
      run: docker run jasmine
