name: Karma Jasmine Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        install-dependencies: true
        install-chromedriver: true
    - uses: actions/setup-node@v4
      with:
        node-version: 16.17.1
    - name: Install packages
      run: npm install
    - name: Run
      run: npm run ng test
